### ISSUE TITLE
What is the difference between drcctprof and go pprof

### ISSUE THREAD

**Issue by zdyj3170101136** [Xuhpclab/DrCCTProf#57]
Hi, i am a new starter of this package.
I am famliar with go pprof.
I want to know what is the difference between go pprof and this package.

**Comment by xl10** [comment]
Hello, DrCCTProf is a fine-grained analysis tool, which targets general each binary instruction dynamically (the binary can be compiled from C/C++/Go/,..), while PProf is a coarse-grained profiler for Go programs. 

We have a unified analysis and visualization framework (https://www.easyview.dev) that can analyze both DrCCTProf and pprof outputs.
