### ISSUE TITLE
DrCCTProf requires Old Versions of CMake, GCC

### ISSUE THREAD

**Issue by jsalzbergedu** [Xuhpclab/DrCCTProf#9]
`sh build.sh` fails when using cmake 13.17.3 and gcc 10.

This is related to two issues in building dynamorio:
[one with cmake,](https://github.com/DynamoRIO/dynamorio/issues/4370)and [one with gcc 10](https://github.com/DynamoRIO/dynamorio/issues/4363).

To solve this on my computer, I had to
1. Wget an old version of cmake and add it to my path:
```bash
wget https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.sh
export PATH=$(realpath ./cmake-3.17.3-Linux-x86_64/bin):$PATH
```
And edit scripts/build_tool/make.sh to use the option `-DCMAKE_C_COMPILER=gcc-9` (instead of `-DCMAKE_C_COMPILER=gcc`) on both line 45 and line 47.

After those changes were made, I was able to compile DrCCTProf using `sh build.sh`.

Thanks :)

**Comment by dolanzhao** [comment]
Could you provide us with complete information about the error you encountered? We recommend you use the template below to report the issue. That will help us to solve your problems quickly.

---
**Describe the error**

A clear and concise description of what the error is.

**Screenshots or Pasted Text**

Please provide screenshots or pasted texts of logs/cmake.log.$TIMESTAMP and logs/make.log.$TIMESTAMP.
For text, please cut and paste the text here, delimited by lines consisting of three backtics to render it verbatim, like this:
<pre>
```
paste output here
```
</pre>

**Information on your system:**

 - CPU Info: [eg. arch@aarch64 model_name@ThunderX2_99xx]
 - System Version: [e.g. Ubuntu14.04]
 - Depand Package Version: [e.g. gcc@10.1, binutils@2.26, cmake@3.7, perl@v5.30.0]

**Additional context**

Add any other context about the problem here.

**Comment by jsalzbergedu** [comment]
**Describe the error**
Using newer versions of gcc and cmake result in DrCCTProf failing to build in the "make" stage.

**Screenshots or Pasted Text**

When using cmake 3.18.1, when I run the following code:
```bash
sh build.sh
```
the "make" log will  contain this error:
```
[  4%] Building ASM object core/CMakeFiles/dynamorio_static.dir/arch/x86/x86.asm.o
cd /dynamorio/build/core && /usr/bin/cpp  -O2 -g -DNDEBUG -fPIC -I/dynamorio/core/drlibc -I/dynamorio/core/ir/x86 -I/dynamorio/core/arch/x86 -I/dynamorio/core/unix -I/dynamorio/core/ir -I/dynamorio/core/arch -I/dynamorio/core/lib -I/dynamorio/build -I/dynamorio/build/include/annotations --defsym STATIC_LIBRARY -DCPP2ASM -E /dynamorio/core/arch/x86/x86.asm -o CMakeFiles/dynamorio_static.dir/arch/x86/x86.asm.o.s
cpp: error: STATIC_LIBRARY: No such file or directory
cpp: warning: '-x c' after last input file has no effect
cpp: error: unrecognized command line option '--defsym'
cpp: fatal error: no input files
compilation terminated.
core/CMakeFiles/dynamorio_static.dir/build.make:838: recipe for target 'core/CMakeFiles/dynamorio_static.dir/arch/x86/x86.asm.o' failed
make[2]: *** [core/CMakeFiles/dynamorio_static.dir/arch/x86/x86.asm.o] Error 1
make[2]: Leaving directory '/dynamorio/build'
CMakeFiles/Makefile2:751: recipe for target 'core/CMakeFiles/dynamorio_static.dir/all' failed
make[1]: *** [core/CMakeFiles/dynamorio_static.dir/all] Error 2
make[1]: Leaving directory '/dynamorio/build'
Makefile:170: recipe for target 'all' failed
make: *** [all] Error 2
```

If I then downgrade to an older version of cmake, and using my system version of gcc (10.1.0), I get the following error in the make log:
```
In file included from dynamorio/tools/drdeploy.c:67:
dynamorio/tools/drdeploy.c: In function ‘append_client’:
dynamorio/libutil/dr_frontend.h:108:23: error: ‘snprintf’ argument 4 may overlap destination object ‘client_paths’ [-Werror=restrict]
  108 | #    define _snprintf snprintf
dynamorio/tools/drdeploy.c:751:9: note: in expansion of macro ‘_snprintf’
  751 |         _snprintf(client_paths[index], BUFFER_SIZE_ELEMENTS(client_paths[index]), "%s",
      |         ^~~~~~~~~
dynamorio/tools/drdeploy.c:737:20: note: destination object referenced by ‘restrict’-qualified argument 1 was declared here
  737 |               char client_paths[MAX_CLIENT_LIBS][MAXIMUM_PATH],
      |               ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

editing scripts/build_tool/make.sh to change -DCMAKE_C_COMPILER fixes this.

**Information On Your System**

- CPU Info: x86_64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
- System Version: Arch Linux
- Dependent package versions: gcc@10.1 cmake@3.18.1

**Additional Context**

The main reason I am reporting this issue here is because you have to edit the build scripts to use gcc < 10, when I would expect setting `$CC` and `$CXX` to work.

**Comment by elihunter173** [comment]
After 65f224039f10939cf350b80468d82d239586c9ff I only need to downgrade cmake. My error is the same as @jsalzbergedu's.

**Information on your system:**

 - CPU Info: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
 - System Version: Arch Linux
 - Dependent Package Version: gcc@10.1.0 cmake@3.18.1

**Comment by quixotrykd** [comment]
I run into the same error as above with cmake@3.18.1 on full updated Arch.

Building the tool on a mounted volume with dockerized Ubuntu 18.04 image seemed to be a good middle ground for me.

I have been using `docker run -v /home/quantatic/DrCCTProf:/DrCCTProf -it ubuntu:18.04 /bin/bash` to build the binary, and then running the binary from within my host system.

**Comment by quixotrykd** [comment]
I run into the same error as above with cmake@3.18.1 on full updated Arch.

Building the tool on a mounted volume with dockerized Ubuntu 18.04 image seemed to be a good middle ground for me, as a temporary fix.

I have been using docker run -v /home/quantatic/DrCCTProf:/DrCCTProf -it ubuntu:18.04 /bin/bash to build the binary, and then running the binary from within my host system.

**Comment by dolanzhao** [comment]
Thanks all!  Let me introduce my solution.

To support NinJa, cmake 3.18+ changed generated defined flags for asm compiling. Specifically, it replaces "-D" with "--defsym " in generated flags.make. 

Using cmake3.18+ to config dynamorio will generate flags define files that contain "--defsym " in three module's dir: 

* ${build path}/core/CMakeFiles/dynamorio.dir
* ${build path}/core/CMakeFiles/dynamorio_static.dir
* ${build path}/ext/drwrap/CMakeFiles/drwrap.dir

And Dynamorio can not build the above three modules correctly.

Without changing the compilation architecture of dynamorio, I fix this error by using a temp solution that is just running a script to replace "--defsym " to "-D" between cmake and make.

Now pulling the lastest commit in master, you all can use cmake 3.18+ to configure our program. And if future dynamorio support gcc10+ and cmake3.18+, I will remove the fix patches ([patch 1](https://github.com/Xuhpclab/DrCCTProf/commit/65f224039f10939cf350b80468d82d239586c9ff), [patch 2](https://github.com/Xuhpclab/DrCCTProf/commit/07abf0c67fcb1ba97838147f1a5e01c35f7f656d)).

Also, if you want to develop a new client, I recommend using gcc <= 9 and cmake <= 3.17 to build our tool. It will ensure you build a stable dynamorio.

**Comment by fuzzah** [comment]
> Thanks all! Let me introduce my solution.
> 
> To support NinJa, cmake 3.18+ changed generated defined flags for asm compiling. Specifically, it replaces "-D" with "--defsym " in generated flags.make.
> 
> Using cmake3.18+ to config dynamorio will generate flags define files that contain "--defsym " in three module's dir:
> 
>     * ${build path}/core/CMakeFiles/dynamorio.dir
> 
>     * ${build path}/core/CMakeFiles/dynamorio_static.dir
> 
>     * ${build path}/ext/drwrap/CMakeFiles/drwrap.dir
> 
> 
> And Dynamorio can not build the above three modules correctly.
> 
> Without changing the compilation architecture of dynamorio, I fix this error by using a temp solution that is just running a script to replace "--defsym " to "-D" between cmake and make.
> 
> Now pulling the lastest commit in master, you all can use cmake 3.18+ to configure our program. And if future dynamorio support gcc10+ and cmake3.18+, I will remove the fix patches ([patch 1](https://github.com/Xuhpclab/DrCCTProf/commit/65f224039f10939cf350b80468d82d239586c9ff), [patch 2](https://github.com/Xuhpclab/DrCCTProf/commit/07abf0c67fcb1ba97838147f1a5e01c35f7f656d)).
> 
> Also, if you want to develop a new client, I recommend using gcc <= 9 and cmake <= 3.17 to build our tool. It will ensure you build a stable dynamorio.

Thank you for this fix idea.
Command to replace defsym to D in all files (run from build directory):
```
grep -rl '\-\-defsym' . | xargs -I% sed -i 's|--defsym|-D|g' %
```
